// Exact editorial substitutions for the nightly presentation pass.
// Kept as review evidence; does not run on the public site.
const fs = require('node:fs');
const routes = JSON.parse(fs.readFileSync('firebase.json')).hosting.rewrites;
const replacements = [
 ['dùng calculator, classifier, splitter và worksheet chỉ khi học liệu cung cấp đủ logic; các phương pháp thiếu công thức được giữ ở chế độ manual/thực hành có hướng dẫn.', 'dùng máy tính, bài phân loại và bảng thực hành để kiểm tra cách làm; luyện từng bước với các bài thực hành có hướng dẫn.'],
 ['📌 Perpetual system is the transaction-workflow scope. Slides also name the periodic system, but no unsupported periodic engine is built here.', '📌 Thực hành nghiệp vụ theo phương pháp kê khai thường xuyên (perpetual). Phương pháp kiểm kê định kỳ (periodic) được giới thiệu để đối chiếu.'],
 ['Same slide-side pattern as Account 152', 'Cách hạch toán tương tự Account 152'],
 ['Feedback is course-supported, not an official lecturer answer key.', 'Dùng phần nhận xét để đối chiếu lập luận và cách hạch toán.'],
 ['This board is grouped from the canonical account rows; it is not presented as a universal lecturer rule beyond those được minh họa trong bài patterns.', 'Đối chiếu từng nhóm tài khoản với nghiệp vụ cụ thể trước khi áp dụng.'],
 ['Lecture slides: straight-line, declining-balance, units-of-production.', 'Các phương pháp: straight-line, declining-balance, units-of-production.'],
 ['Slides: Receivables and Payables, with receivables/payables, VAT, current CIT and borrowings core.', 'Trọng tâm: Receivables and Payables, VAT, current CIT và borrowings.'],
 ['Slides mention perpetual and periodic systems.', 'Hai phương pháp: perpetual và periodic.'],
 ['gom những cặp dễ nhầm, bảng so sánh và ví dụ giảng viên thành cụm ôn nhanh thay vì học rời từng slide.', 'ôn theo cụm khái niệm dễ nhầm, bảng so sánh và ví dụ để kết nối kiến thức.'],
 ['Công thức relative-ratio trên slide bị phân mảnh trong phần trích xuất. Trang này chỉ giữ semantic rule và ví dụ số đã xác minh; chỉ trình bày lại chuỗi ký hiệu chưa được kiểm tra từ slide gốc.', 'Đối chiếu quy tắc chi phí tương đối với ví dụ số trước khi kết luận lợi thế so sánh.'],
 ['Physical-unit Kết luận: Britain capital abundant; America labor abundant. The factor-price follow-up is left without lecturer-provided answer.', 'Kết luận theo đơn vị hiện vật: Britain capital abundant; America labor abundant. Phần giá yếu tố sản xuất là câu hỏi tự luyện, chưa có lời giải mẫu.'],
 ['Lecturer classifies tariff as an indirect tax because', 'Thuế quan là thuế gián thu vì'],
 ['ba Các vụ việc minh họa mà không mở rộng ra ngoài dữ liệu bài giảng.', 'ba vụ việc minh họa.'],
 ['Gom theory, formula, graph cues, confusion pairs và lecturer examples của Chapters 1–4 vào một hub ôn tập;', 'Ôn lý thuyết, công thức, cách đọc đồ thị, cặp dễ nhầm và ví dụ của Chapters 1–4;'],
 ['Lecturer limitation / note', 'Lưu ý khi vận dụng'],
 ['Lecturer example index', 'Danh mục ví dụ'],
 ['Lecturer evaluation', 'Nhận xét'], ['Lecturer examples', 'Ví dụ minh họa'], ['Lecturer example', 'Ví dụ minh họa'], ['Learning lens', 'Góc nhìn học tập'],
 ['theo đúng học liệu môn học', 'qua các khái niệm và tình huống minh họa'],
 ['các mức thuế, mốc thời gian và ví dụ HS được giữ nguyên để bạn luyện đọc chính xác dữ liệu bài giảng.', 'luyện đọc chính xác mức thuế, mốc thời gian và các ví dụ HS.'],
 ['chủ thể được slide nêu là', 'chủ thể là'], [' theo cách định nghĩa của slide', ''],
 ['Các hình dưới là sơ đồ học thuật tối giản. Học liệu văn bản không có hình học tuyến đường gốc, nên chỉ giữ các quan hệ và địa danh đã được ghi lại.', 'Sơ đồ giúp nối các địa danh và quan hệ thương mại; không biểu diễn tuyến đường theo tỷ lệ địa lý.'],
 ['Được slide gọi là mạng lưới thương mại quốc tế đầu tiên.', 'Mạng lưới thương mại quốc tế đầu tiên.'],
 ['slide còn nhắc amber road', 'cùng tuyến amber road'],
 ['Mốc thời kỳ được giữ đúng theo slide.', 'Ghi nhớ mốc thời kỳ này khi đối chiếu các tư tưởng thương mại.'],
 ['Growth figures trong slide', 'Số liệu tăng trưởng'],
 ['Số liệu theo bài giảng; không phải xác minh hiện tại.', 'Số liệu lịch sử để luyện phân tích, không phải số liệu hiện hành.'],
 ['Act of State/doctrinal example; học liệu không cung cấp full case brief.', 'Ví dụ về học thuyết Act of State; phần tóm tắt không bao quát toàn bộ vụ việc.'],
 ['học liệu figures', 'Số liệu tham khảo'],
 ['Slide identifies Ngozi Okonjo-Iweala as 7th Director-General and first woman DG; names Renato Ruggiero as first Director-General. Các mô tả này được giữ như trạng thái học liệu, không phải xác minh hiện tại.', 'Ngozi Okonjo-Iweala: 7th Director-General và nữ DG đầu tiên; Renato Ruggiero: first Director-General. Thông tin dùng để ôn tập lịch sử tổ chức, không phải cập nhật nhân sự hiện tại.'],
 ['TPR frequency shown in slide', 'Chu kỳ TPR'],
 ['xem đúng nhóm hiệp định mà bài giảng liệt kê', 'xem từng nhóm hiệp định'],
 ['được bài giảng nhấn mạnh', 'cần ghi nhớ'],
 ['GATS II.1 / TRIPS IV — proposition theo slide', 'GATS II.1 / TRIPS IV — nội dung quy định'],
 ['được slide dùng với metaphor', 'minh họa bằng hình ảnh'], ['slide nói vodka', 'vodka'],
 ['không được slide dùng làm basis để phân biệt', 'không được dùng làm căn cứ phân biệt'],
 ['slide reproduces panel proposition rằng', 'nhận định của ban hội thẩm nêu rằng'],
 ['Ghép case với proposition đúng trong học liệu', 'Ghép vụ việc với nhận định phù hợp'],
 ['Được slide trình bày rộng hơn', 'Có phạm vi rộng hơn'],
 ['Slide asks “What is protection?” nhưng không định nghĩa.', 'Câu hỏi tự luyện: “What is protection?”'],
 ['slide refers to Paris, Berne and Rome treaties.', 'Liên hệ các điều ước Paris, Berne và Rome.'],
 ['Lecturer file không cung cấp final factual application/conclusion. Dùng III.2 first/second sentence frameworks, nhưng không biến organizer thành “official answer”.', 'Tự lập luận theo khung III.2 first/second sentence. Đây là bài luyện phân tích, chưa có kết luận mẫu.'],
 ['bằng đúng dữ liệu và method scope của học liệu', 'qua dữ liệu và phương pháp minh họa'],
 ['Học liệu chỉ cho coefficient 25, starting lines 150/125/100/75/50/25/10%, x-axis Year 0–6 và trend:', 'Ví dụ sử dụng coefficient 25, starting lines 150/125/100/75/50/25/10%, x-axis Year 0–6 và xu hướng:'],
 ['Appellate review scope in slide model?', 'Phạm vi xem xét phúc thẩm?'],
 ['Accounting — định nghĩa theo slide Luật Kế toán', 'Accounting — định nghĩa theo Luật Kế toán'],
 ['Slides đồng thời dẫn các định nghĩa từ', 'Đối chiếu thêm các định nghĩa từ'],
 ['một slide mô tả thông tin cho người dùng ngoài là “absolutely accurate”, trong khi slide về true/fair và materiality nói báo cáo không nhất thiết tuyệt đối chính xác và có thể chấp nhận sai lệch không trọng yếu. Lưu ý: cả hai cách diễn đạt, không tự hòa giải thành một quy tắc mới.', 'Cần phân biệt cách diễn đạt “absolutely accurate” về thông tin cho người dùng ngoài với true/fair và materiality: báo cáo không nhất thiết tuyệt đối chính xác và có thể chấp nhận sai lệch không trọng yếu. Hai cách diễn đạt này cần được xem trong ngữ cảnh riêng.'],
 ['học liệu yêu cầu tự nghiên cứu hệ thống văn bản pháp lý kế toán Việt Nam, nguyên tắc đạo đức nghề nghiệp và so sánh loại hình doanh nghiệp nhưng không cung cấp đáp án mẫu. Trang chỉ giữ prompt, không tự thêm “đáp án chuẩn”.', 'Tự nghiên cứu hệ thống văn bản pháp lý kế toán Việt Nam, nguyên tắc đạo đức nghề nghiệp và so sánh loại hình doanh nghiệp. Đây là câu hỏi mở, chưa có đáp án mẫu.'],
 ['Lecturer-bài học MCQ replay', 'Luyện câu hỏi trắc nghiệm'],
 ['theo đúng wording của slide.', 'theo cách diễn đạt của từng khái niệm.'],
 ['slides 35–36 và slide 37 gán số thứ tự khác nhau cho một số line item (đặc biệt net operating profit / other income / other expense). Hoạt động dưới đây chấm theo', 'Có hai cách đánh số khác nhau cho một số line item (đặc biệt net operating profit / other income / other expense). Hoạt động dưới đây chấm theo'],
 ['chưa có đáp án giảng viên', 'chưa có lời giải mẫu'],
 ['Lưu ý: đây là bài chưa có kết quả mẫu; calculator chung chỉ sử dụng đúng các công thức đã cung cấp, không gắn nhãn “đáp án giảng viên”.', 'Bài tự luyện chưa có kết quả mẫu. Dùng máy tính công thức để kiểm tra từng bước tính.'],
 ['112 (slide: Cash in banks)', '112 (Cash in banks)'],
 ['bài học cho batch instructions nhưng để trống số tính. Nội dung chưa cung cấp kết quả như thể là đáp án giảng viên.', 'Làm lần lượt các yêu cầu và tự tính kết quả; bài này chưa có lời giải mẫu.'],
 ['bài periodic bắt đầu bằng “Khoi &amp; Ngo Company” nhưng requirement lại nhắc “Tuan &amp; Tu Company”. Giữ nguyên cảnh báo, không tự đổi tên.', 'Lưu ý tên doanh nghiệp trong bài periodic chưa thống nhất: phần đầu là “Khoi &amp; Ngo Company”, yêu cầu là “Tuan &amp; Tu Company”.'],
 ['Computerized accounting chọn một trong bốn hình thức theo slide.', 'Computerized accounting chọn một trong bốn hình thức.'],
 ['narrative nói transportation cost xảy ra Sep 19, nhưng General Journal row ghi 18/9. Cả hai ngày được giữ, không tự “sửa”.', 'Ngày transportation cost chưa thống nhất: mô tả ghi Sep 19, General Journal ghi 18/9. Chú ý khác biệt này khi đối chiếu.'],
 ['học liệu data only:', 'Dữ liệu thực hành:'],
 ['bảng tỷ lệ được giữ đúng theo slide và chưa được external verification về hiệu lực pháp lý hiện tại.', 'Bảng tỷ lệ dùng cho bài tập, chưa xác nhận hiệu lực pháp lý hiện tại.'],
 ['Tra cứu toàn bộ danh sách tài khoản song ngữ được cung cấp trong học liệu, theo code, English, Vietnamese và code depth — không suy diễn ý nghĩa chữ số ngoài cấu trúc đã nêu.', 'Tra cứu tài khoản theo mã, tên tiếng Anh, tên tiếng Việt và độ sâu của mã.'],
 ['slide chỉ giải thích ý nghĩa đến chữ số thứ 4, trong khi chart có mã 5–6 chữ số như 41111, 215121, 82111. Các mã sâu được giữ nguyên tên/code nhưng không gán thêm semantics cho vị trí thứ 5/6.', 'Cấu trúc mã được giải thích đến chữ số thứ 4. Với mã 5–6 chữ số như 41111, 215121, 82111, hãy tra cứu theo tên và mã; không suy rộng quy tắc sang vị trí thứ 5/6.'],
 ['10 điểm dễ nhầm từ chính học liệu', '10 điểm dễ nhầm'], ['Phạm vi học liệu:', 'Nội dung ôn tập:'],
 ['theo đúng phạm vi học liệu đã cung cấp', 'qua khái niệm, ví dụ và bài thực hành'],
 ['Một sơ đồ DERIVED từ các mô tả đã được trích xuất; không khẳng định đây là bản sao layout của slide p.21.', 'Sơ đồ tóm tắt các mối quan hệ để dễ đối chiếu.'],
 ['Chỉ dùng instruments lecturer liệt kê.', 'Đối chiếu các công cụ tài chính dưới đây.'],
 ['Lecturer advantages:', 'Ưu điểm:'], ['Công cụ lecturer liệt kê', 'Các công cụ tài chính'],
 ['Không chạy calculation cho tới khi exponent typography ở slide gốc được verify.', 'Chưa đủ thông tin về số mũ để tính kết quả.'],
 ['Không được tự giả định vị trí exponent khi slide gốc chưa được verify.', 'Cần xác định rõ vị trí số mũ trước khi áp dụng công thức.'],
 [', per lecturer terminology.', '.'],
 ['Platform dùng official syllabus numbering Ch.1–Ch.6. Original lecturer deck labels for Asset Demand / Interest Rate / Foreign Exchange differ and are retained only as bài học-history context, not navigation.', 'Ôn lần lượt Ch.1–Ch.6; kết nối Asset Demand, Interest Rate và Foreign Exchange khi tổng hợp kiến thức.'],
 ['One of the five lecturer-listed sustainable-development principles.', 'Một trong năm nguyên tắc phát triển bền vững.'],
 ['học liệu claim · không phải dữ liệu cập nhật theo thời gian thực', 'Số liệu tham khảo theo thời điểm'],
 ['Lecturer slide attributes the multidimensional-poverty statistic to', 'Thống kê nghèo đa chiều được dẫn từ'],
 ['and references the', 'và liên hệ với'], ['framing.</div>', '.</div>'],
 ['Lecturer-listed benefit', 'Lợi ích'],
 ['Các mini-scenario dưới đây chỉ được suy ra trực tiếp từ wording của bài, không phải case chính thức của giảng viên.', 'Đọc từng tình huống ngắn và chọn nhóm phù hợp.'],
 ['học liệu dates — không phải dữ liệu cập nhật theo thời gian thực:', 'Mốc thời gian tham khảo:'],
 ['Examples named in the bài học include UN, WB, ADB, EU, IMF, OECD and Green Climate Fund. International-commitment examples named include', 'Ví dụ: UN, WB, ADB, EU, IMF, OECD và Green Climate Fund. Các cam kết quốc tế tiêu biểu:'],
 ['. The lecturer slide also uses IMF/WB structural-reform requirements as examples of strict policy/loan conditions. Use these only as bài học-bounded examples.', '. Yêu cầu cải cách cơ cấu của IMF/WB minh họa điều kiện chính sách hoặc vay vốn nghiêm ngặt.'],
 ['học liệu framing · 2021–2030 integration noted in bài học', 'Lồng ghép giai đoạn 2021–2030'],
 ['slide mô tả Việt Nam là', 'Việt Nam là'], ['Slide mô tả Việt Nam thuộc', 'Việt Nam thuộc'],
 ['Time-specific claims preserved as học liệu claims', 'Nhận định theo thời điểm'],
 ['Slide states an estimated stop to production/import of gasoline vehicles around 2040–2045', 'Ước tính dừng sản xuất/nhập khẩu xe xăng khoảng 2040–2045'],
 ['“Điểm sáng” trong slide', 'Điểm sáng'], ['được slide mô tả là', 'là'],
 ['Các mốc và mô tả được giữ nguyên như học liệu claims; không live-update.', 'Các mốc và nhận định mang tính tham khảo theo thời điểm.'],
 ['Chỉ dùng các items được slide liệt kê; không bổ sung đánh giá hiện tại.', 'Phân loại từng nhận định thành thành tựu hoặc hạn chế.'],
 ['Achievements vs Limitations vs Solutions; time-specific claims remain học liệu claims', 'Thành tựu, hạn chế và giải pháp; chú ý thời điểm của từng nhận định'],
 ['Enhancers listed by the lecturer:', 'Các yếu tố hỗ trợ:'],
 ['. Không tự điền subtopic chưa được trích.', '.'],
 ['Bài học cho 20 phút chuẩn bị; workspace không tự chấm vì không có đáp án mẫu.', 'Dành 20 phút chuẩn bị và tự đối chiếu lập luận; bài này không chấm điểm tự động.'],
 ['Critical Thinking trong slide là', 'Critical Thinking là'],
 ['Hai loại theo đúng thuật ngữ giảng viên:', 'Hai loại:'],
 ['Slide mở rộng dùng nhãn “Context” cho phần mô tả', '“Context and Integration” còn được gọi ngắn là “Context”'],
 ['slide đánh dấu START HERE tại Desirability', 'bắt đầu tại Desirability'],
 ['slide còn đối chiếu', 'đối chiếu thêm'], ['slide minh họa ba speech acts', 'ba speech acts được minh họa'],
 ['Slide gắn lần lượt với ví dụ Tesla, Apple, Airbnb, Amazon — đây là các ví dụ thảo luận trong bài.', 'Ví dụ lần lượt: Tesla, Apple, Airbnb, Amazon.'],
 ['Các company/person examples là học liệu examples; không phải independently verified trong page này.', 'Dùng các ví dụ doanh nghiệp và cá nhân để thảo luận đặc điểm khởi nghiệp.'],
 ['Slide trích số 92% người Mỹ cho rằng entrepreneurs cực kỳ quan trọng với tạo việc làm; con số này được giữ theo bài học course, không tự xác minh ngoài.', 'Số liệu tham khảo: 92% người Mỹ cho rằng entrepreneurs cực kỳ quan trọng với tạo việc làm.'],
 ['A slide gives a generic example:', 'Ví dụ:'], ['slide nêu 40%–50%', '40%–50%'],
 ['Another slide defines entrepreneurship as the process of', 'Một định nghĩa khác: entrepreneurship là quá trình'],
 ['slide entrepreneur characteristics cũng có', 'nhóm entrepreneur characteristics cũng có'],
 ['Slide sau mở rộng bằng các nhãn', 'Có thể đối chiếu với các nhãn'],
 ['Myth vs Facts — học liệu cases', 'Quan niệm và thực tế — tình huống minh họa'],
 ['dòng chú thích on slide:', 'Tài liệu tham khảo:'],
 ['học liệu claim — dùng cho mục đích học tập', 'Tình huống để thảo luận'],
 ['Slide claims:', 'Tóm tắt tình huống:'],
 ['Giữ đúng Convergent = “tự điều chỉnh”; Divergent = “ngoại cảnh” theo lecturer material.', 'Phân biệt Convergent = “tự điều chỉnh”; Divergent = “ngoại cảnh”.'],
 ['. Lưu ý: các biến thể này tách biệt, không tự chuẩn hóa.', '. Lưu ý phân biệt các biến thể này.'],
 ['Các field names được giữ lại, nhưng salary-range values không còn trong dữ liệu gốc; không tự tạo range.', 'Bảng chưa có khoảng lương để đối chiếu.'],
 ['Giữ đúng labels short / medium / longer / long term; không tự gán số năm.', 'Phân biệt short / medium / longer / long term; các nhóm này chưa gắn với số năm cụ thể.'],
 ['Rows/product names của bảng không được trích xuất, nên không tự tạo danh sách sản phẩm life/non-life.', 'Phần này chưa có danh sách sản phẩm life/non-life để đối chiếu.'],
 ['Bài học tension — không tự sửa', 'Hai cách diễn đạt cần phân biệt'],
 ['Long / intermediate / short; bài học slide mentions SMART vs HARD', 'Long / intermediate / short; đối chiếu SMART vs HARD'],
 ['Không có lecturer/model solution', 'Bài tự luyện chưa có lời giải mẫu'],
 ['Các facts dưới đây đến từ official question-bank feedback và có thể mở rộng ra ngoài theory slide đã phát triển đầy đủ. Chúng được giữ', 'Các điểm ghi nhớ dưới đây giúp ôn thêm kiến thức qua câu hỏi luyện tập. Sử dụng'],
 ['; trang không mở rộng bằng kiến thức ngoài và không đưa 150 câu hỏi/options vào Theory.', '; luyện 150 câu hỏi tại phần Luyện đề.'],
 ['theo đúng phạm vi học liệu đã được cung cấp', 'qua khái niệm và ví dụ thực hành'],
 ['a lecturer-worked answer.', 'a worked solution.'],
 ['Giữ đúng module chính thức trong course map và thể hiện rõ trạng thái thiếu học liệu; không backfill stages, theorists, models hay examples từ kiến thức ngoài phạm vi bài.', 'Nội dung chương đang được bổ sung. Bạn có thể tiếp tục ôn các chương đã có bài học và bài thực hành.'],
 ['slide nêu vật chất/entrepreneurship', 'vật chất/entrepreneurship'],
 ['Political & economic systems — học liệu summary', 'Hệ thống chính trị và kinh tế — tóm tắt'], ['học liệu framing', 'Góc nhìn phân tích'],
 ['Content theories shown on overview slide', 'Các lý thuyết nội dung'], ['Process theories shown on overview slide', 'Các lý thuyết quá trình'], ['Detailed focus in later slides:', 'Nội dung trọng tâm:'],
 ['Nhãn anomaly preserved: the country plot sits under Achievement Motivation Theory, while its slide subheading says “International Findings on Two-Factor Theory.”', 'Lưu ý khác biệt giữa nhãn và nội dung: biểu đồ quốc gia nằm trong Achievement Motivation Theory nhưng có tiêu đề “International Findings on Two-Factor Theory.”'],
 ['Examples are học liệu cases, not universal rules about everyone in a country.', 'Các tình huống minh họa không đại diện cho tất cả mọi người trong một quốc gia.'],
 ['actual operation tạo bất lợi', 'cách áp dụng trên thực tế tạo bất lợi'],
 ['Source practice', 'Ví dụ luyện tập'], ['source practice', 'ví dụ luyện tập'],
];
const log = [];
for (const route of routes) {
 const file = route.destination.slice(1);
 let source = fs.readFileSync(file, 'utf8');
 if (route.source === '/PTBV') {
  const start = source.indexOf(' <div class="mt-7 max-w-4xl mx-auto text-left">');
  const end = source.indexOf(' </section>', start);
  if (start >= 0 && end >= 0) source = source.slice(0, start) + source.slice(end);
 }
 for (const [before, after] of replacements) {
  if (source.includes(before)) {
   log.push({file, before, after, count: source.split(before).length - 1});
   source = source.split(before).join(after);
  }
 }
 fs.writeFileSync(file, source);
}
fs.writeFileSync('tests/editorial-results.json', JSON.stringify(log, null, 2));
console.log(`${log.length} exact editorial substitutions across ${new Set(log.map(x=>x.file)).size} pages; PTBV administrative map removed.`);
