const fs=require('node:fs'),path=require('node:path');
const {chromium}=require('playwright');
const fixture=fs.readFileSync(path.join(__dirname,'firebase-fixture.js'),'utf8');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:390,height:844}});p.on('dialog',d=>d.accept());
 await p.addInitScript(()=>window.__fixtureOptions={user:{uid:'test-user',email:'student@example.test',displayName:'Sinh viên'}});
 await p.route(/https:\/\/www\.gstatic\.com\/firebasejs\/.+\.js/,r=>r.fulfill({contentType:'text/javascript',body:r.request().url().includes('firebase-app-compat')?fixture:''}));
 await p.goto('http://127.0.0.1:4173/NguyenLyKeToan-LuyenDe');
 await p.getByRole('button',{name:'Bắt đầu luyện theo chương',exact:true}).click();
 await p.getByRole('button',{name:'Mở bài luyện',exact:true}).first().click();
 await p.locator('.option-card').nth(1).click();await p.locator('.option-card').first().click();
 await p.getByRole('button',{name:'Nộp bài',exact:true}).click();await p.getByRole('button',{name:'Nộp bài',exact:true}).click();
 console.log('NLKT duplicate writes',await p.evaluate(()=>__firebaseTest.writes.filter(w=>w.path==='accountingAttempts').length));
 console.log('NLKT result',await p.locator('#result-box').innerText());
 await p.screenshot({path:path.join(__dirname,'screenshots/round2/before-NLKT-result.png')});
 await p.getByRole('button',{name:'Làm lại',exact:true}).click();
 await p.getByRole('button',{name:'← Quay lại danh sách',exact:true}).click();
 console.log('NLKT back tab',await p.locator('.tab-content:visible').getAttribute('id'));
 await p.goto('http://127.0.0.1:4173/TCCN-LuyenDe');
 await p.getByRole('button',{name:'Vào luyện thi',exact:true}).click();
 await p.getByRole('button',{name:'Bắt đầu làm bài',exact:true}).first().click();
 await p.locator('.answer-btn').first().click();
 await p.getByRole('button',{name:'Nộp bài',exact:true}).click();await p.getByRole('button',{name:'Nộp bài',exact:true}).click();
 console.log('TCCN duplicate attempts',await p.evaluate(()=>getAttempts().length));
 console.log('TCCN unanswered label',await p.locator('.question-card').nth(1).innerText());
 await p.screenshot({path:path.join(__dirname,'screenshots/round2/before-TCCN-result.png')});
 await p.evaluate(()=>localStorage.setItem('edu_tccn_wrong_ids_v1','{}'));
 const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.reload();
 console.log('TCCN malformed storage errors',errors);
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
